#ifndef PINDEFINITION_H_INCLUDED
#define PINDEFINITION_H_INCLUDED

#define BLUEFRUIT_SPI_CS 8
#define BLUEFRUIT_SPI_IRQ 7
#define BLUEFRUIT_SPI_RST 4

#define ADCPIN A3
#define SD_PIN  12
#define ACCELEROMETRE_IT 10
#define BTN_1 6
#define BTN_2 5
#define LED_RED 13
#define LED_GREEN 11

#define VIBREUR A0

#endif // PINDEFINITION_H_INCLUDED
